<Project>
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
        <TestTargetFrameworks>net10.0</TestTargetFrameworks>
        <TestTargetFrameworks Condition=" '$(CI)' != 'true' And $([MSBuild]::IsOsPlatform('Windows')) ">net481;$(TestTargetFrameworks)</TestTargetFrameworks>
    </PropertyGroup>
</Project>
