// <auto-generated>
//     This code was generated by ToonFormat.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Nodes;
using Toon.Format;
using Xunit;


namespace Toon.Format.Tests.Decode;


[Trait("Category", "decode")]
public class Whitespace
{
    [Fact]
    [Trait("Description", "tolerates spaces around commas in inline arrays")]
    public void ToleratesSpacesAroundCommasInInlineArrays()
    {
        // Arrange
        var input =
"""
tags[3]: a , b , c
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = JsonNode.Parse("""
{"tags":["a","b","c"]}
""");

        Assert.True(JsonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "tolerates spaces around pipes in inline arrays")]
    public void ToleratesSpacesAroundPipesInInlineArrays()
    {
        // Arrange
        var input =
"""
tags[3|]: a | b | c
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = JsonNode.Parse("""
{"tags":["a","b","c"]}
""");

        Assert.True(JsonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "tolerates spaces around tabs in inline arrays")]
    public void ToleratesSpacesAroundTabsInInlineArrays()
    {
        // Arrange
        var input =
"""
tags[3	]: a 	 b 	 c
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = JsonNode.Parse("""
{"tags":["a","b","c"]}
""");

        Assert.True(JsonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "tolerates leading and trailing spaces in tabular row values")]
    public void ToleratesLeadingAndTrailingSpacesInTabularRowValues()
    {
        // Arrange
        var input =
"""
items[2]{id,name}:
  1 , Alice 
  2 , Bob 
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = JsonNode.Parse("""
{"items":[{"id":1,"name":"Alice"},{"id":2,"name":"Bob"}]}
""");

        Assert.True(JsonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "tolerates spaces around delimiters with quoted values")]
    public void ToleratesSpacesAroundDelimitersWithQuotedValues()
    {
        // Arrange
        var input =
"""
items[3]: "a" , "b" , "c"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = JsonNode.Parse("""
{"items":["a","b","c"]}
""");

        Assert.True(JsonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses empty tokens as empty string")]
    public void ParsesEmptyTokensAsEmptyString()
    {
        // Arrange
        var input =
"""
items[3]: a,,c
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = JsonNode.Parse("""
{"items":["a","","c"]}
""");

        Assert.True(JsonNode.DeepEquals(result, expected));
    }

}
