// <auto-generated>
//     This code was generated by ToonFormat.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Nodes;
using Toon.Format;
using Xunit;


namespace ToonFormat.Tests.Decode;


[Trait("Category", "decode")]
public class RootForm
{
    [Fact]
    [Trait("Description", "empty document decodes to empty object")]
    public void EmptyDocumentDecodesToEmptyObject()
    {
        // Arrange
        var input =
"""

""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = JsonNode.Parse("""
{}
""");

        Assert.True(JsonNode.DeepEquals(result, expected));
    }

}
